<?php
namespace Database\Seeders;
use App\Models\Pkp_indicator;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
class PkpIndicatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'program_id' => 1,
                'indicator_code' => 'IP-IND-25-0001',
                'indicator_name' => '100% of target population (0- 12 months) born in January 2024-June 2024 are fully immunized within the rating period.',
                'indicator_description' => '100% of target population (0- 12 months) born in January 2024-June 2024 are fully immunized within the rating period.',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 1,
                'indicator_code' => 'IP-IND-25-0002',
                'indicator_name' => 'Total number of households provided with health promotion services on Immunization',
                'indicator_description' => 'Total number of households provided with health promotion services on Immunization',
                'indicator_status' => 1,
                'indicator_scope' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 2,
                'indicator_code' => 'NP-IND-25-0003',
                'indicator_name' => 'Number of children 6-59 months given Vitamin A',
                'indicator_description' => 'Number of children 6-59 months given Vitamin A',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 2,
                'indicator_code' => 'NP-IND-25-0004',
                'indicator_name' => 'Number of Moderately Acute Malnourished (MAM) and Severely Acute Malnourished (SAM) children monitored and referred for appropriate intervention in OTC and monitored monthly',
                'indicator_description' => 'Number of Moderately Acute Malnourished (MAM) and Severely Acute Malnourished (SAM) children monitored and referred for appropriate intervention in OTC and monitored monthly',
                'indicator_status' => 1,
                'indicator_scope' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 2,
                'indicator_code' => 'NP-IND-25-0005',
                'indicator_name' => 'Number of pregnant women provided with complete dosage of iron with folic acid supplementation as soon as pregnancy is confirmed',
                'indicator_description' => 'Number of pregnant women provided with complete dosage of iron with folic acid supplementation as soon as pregnancy is confirmed',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 2,
                'indicator_code' => 'NP-IND-25-0006',
                'indicator_name' => 'Number of 12-59 months old provided with deworming tablets.',
                'indicator_description' => 'Number of 12-59 months old provided with deworming tablets.',
                'indicator_status' => 1,
                'indicator_scope' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 2,
                'indicator_code' => 'NP-IND-25-0007',
                'indicator_name' => 'Total number of households provided with health promotion services on Nutrition',
                'indicator_description' => 'Total number of households provided with health promotion services on Nutrition',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 3,
                'indicator_code' => 'WASH-IND-25-0008',
                'indicator_name' => 'Total number of households provided with health promotion services on Water supply, Sanitation and Hygiene (WaSH',
                'indicator_description' => 'Total number of households provided with health promotion services on Water supply, Sanitation and Hygiene (WaSH',
                'indicator_status' => 1,
                'indicator_scope' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 3,
                'indicator_code' => 'WASH-IND-25-0009',
                'indicator_name' => 'Total number of households provided with health promotion services on Water supply, Sanitation and Hygiene (WaSH)',
                'indicator_description' => 'Total number of households provided with health promotion services on Water supply, Sanitation and Hygiene (WaSH)',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 4,
                'indicator_code' => 'MH-IND-25-0010',
                'indicator_name' => 'Number of pregnant women tracked given appropriate prenatal services',
                'indicator_description' => 'Number of pregnant women tracked given appropriate prenatal services',
                'indicator_status' => 1,
                'indicator_scope' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 4,
                'indicator_code' => 'MH-IND-25-0011',
                'indicator_name' => 'Number of post-partum women provided with postpartum services within 7 days after delivery',
                'indicator_description' => 'Number of post-partum women provided with postpartum services within 7 days after delivery',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 4,
                'indicator_code' => 'MH-IND-25-0012',
                'indicator_name' => 'Number of WRA (Women of Reproductive Age) provided with appropriate services',
                'indicator_description' => 'Number of WRA (Women of Reproductive Age) provided with appropriate services',
                'indicator_status' => 1,
                'indicator_scope' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 4,
                'indicator_code' => 'MH-IND-25-0013',
                'indicator_name' => 'Total number of households provided with health promotion services on Maternal Health',
                'indicator_description' => 'Total number of households provided with health promotion services on Maternal Health',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 5,
                'indicator_code' => 'TB-IND-25-0014',
                'indicator_name' => 'Number of patients assessed/screened for TB, given proper information and appropriate intervention according to TB guidelines',
                'indicator_description' => 'Number of patients assessed/screened for TB, given proper information and appropriate intervention according to TB guidelines',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 5,
                'indicator_code' => 'TB-IND-25-0015',
                'indicator_name' => 'Total number of households provided with health promotion services on Tuberculosis',
                'indicator_description' => 'Total number of households provided with health promotion services on Tuberculosis',
                'indicator_status' => 1,
                'indicator_scope' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 6,
                'indicator_code' => 'HIV-IND-25-0016',
                'indicator_name' => 'Number of patients (key population) assessed/screened for HIV through Community-based Screening given proper information according to National HIV/AIDS/ STI Prevention and Control Program (NASPC) guidelines.',
                'indicator_description' => 'Number of patients (key population) assessed/screened for HIV through Community-based Screening given proper information according to National HIV/AIDS/ STI Prevention and Control Program (NASPC) guidelines.',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 6,
                'indicator_code' => 'HIV-IND-25-0017',
                'indicator_name' => 'Total number of households provided with health promotion services on HIV/AIDS',
                'indicator_description' => 'Total number of households provided with health promotion services on HIV/AIDS',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 7,
                'indicator_code' => 'RSP-IND-25-0018',
                'indicator_name' => 'Number of adults 20 years old and above assessed using PHILPEN Risk Assessment Form',
                'indicator_description' => 'Number of adults 20 years old and above assessed using PHILPEN Risk Assessment Form',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 7,
                'indicator_code' => 'RSP-IND-25-0019',
                'indicator_name' => 'Number of at risk clients 20 years old and above clients referred for screening and needing further intervention and/or specialized care to the RHU or higher health facilities',
                'indicator_description' => 'Number of at risk clients 20 years old and above clients referred for screening and needing further intervention and/or specialized care to the RHU or higher health facilities',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 7,
                'indicator_code' => 'RSP-IND-25-0020',
                'indicator_name' => 'Total number of households provided with health promotion services on Hypertension',
                'indicator_description' => 'Total number of households provided with health promotion services on Hypertension',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 8,
                'indicator_code' => 'NCD-IND-25-0021',
                'indicator_name' => 'Number of 9-14 years old female vaccinated with complete HPV vaccination',
                'indicator_description' => 'Number of 9-14 years old female vaccinated with complete HPV vaccination',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 8,
                'indicator_code' => 'NCD-IND-25-0022',
                'indicator_name' => 'Number of eligible women between 30-65 years old were referred for cervical cancer screening and management',
                'indicator_description' => 'Number of eligible women between 30-65 years old were referred for cervical cancer screening and management',
                'indicator_status' => 1,
                'indicator_scope' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 8,
                'indicator_code' => 'NCD-IND-25-0023',
                'indicator_name' => 'Number of eligible women between 30-65 years old who gave consent screened for breast mass and referred for management',
                'indicator_description' => 'Number of eligible women between 30-65 years old who gave consent screened for breast mass and referred for management',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 8,
                'indicator_code' => 'NCD-IND-25-0024',
                'indicator_name' => 'Total number of households provided with health promotion services on Cancer',
                'indicator_description' => 'Total number of households provided with health promotion services on Cancer',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 9,
                'indicator_code' => 'MH-IND-25-0025',
                'indicator_name' => 'Number of households provided with health promotion services on Mental Health',
                'indicator_description' => 'Number of households provided with health promotion services on Mental Health',
                'indicator_status' => 1,
                'indicator_scope' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 9,
                'indicator_code' => 'MH-IND-25-0026',
                'indicator_name' => 'Number of individuals screened for risks for mental health disorders using the WHO-SRQ',
                'indicator_description' => 'Number of individuals screened for risks for mental health disorders using the WHO-SRQ',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'program_id' => 9,
                'indicator_code' => 'MH-IND-25-0027',
                'indicator_name' => 'Number of individuals with risks for mental health disorders referred  for further assessment',
                'indicator_description' => 'Number of individuals with risks for mental health disorders referred  for further assessment',
                'indicator_status' => 1,
                'indicator_scope' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

       collect( $data)->each(function($indicator){
             $indicator = Pkp_indicator::create($indicator);
             $indicator->disaggregations()->attach([1]);
       });

    }
}
