<?php

namespace Database\Seeders;

use App\Models\Pkp_site;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PkpSiteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                "site_id" => 1,
                "barangay_id" => 37067,
                "latitude" => 17.5155,
                "longitude" => 120.6181,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 2,
                "barangay_id" => 37068,
                "latitude" => 17.5201,
                "longitude" => 120.6433,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 3,
                "barangay_id" => 37072,
                "latitude" => 17.5167,
                "longitude" => 120.62,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 4,
                "barangay_id" => 37113,
                "latitude" => 17.4725,
                "longitude" => 120.7575,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 950,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 5,
                "barangay_id" => 37114,
                "latitude" => 17.47,
                "longitude" => 120.75,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 6,
                "barangay_id" => 37115,
                "latitude" => 17.465,
                "longitude" => 120.745,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1050,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 7,
                "barangay_id" => 37117,
                "latitude" => 17.541,
                "longitude" => 120.841,
                "site_status" => 4,
                "no_purok" => 3,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 48,
                "population" => 800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 8,
                "barangay_id" => 37118,
                "latitude" => 17.545,
                "longitude" => 120.845,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 100,
                "population" => 750,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 9,
                "barangay_id" => 37119,
                "latitude" => 17.548,
                "longitude" => 120.848,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 78,
                "population" => 850,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 10,
                "barangay_id" => 37156,
                "latitude" => 17.641,
                "longitude" => 121.003,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 168,
                "population" => 600,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 11,
                "barangay_id" => 37164,
                "latitude" => 17.61,
                "longitude" => 120.71,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1300,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 12,
                "barangay_id" => 37171,
                "latitude" => 17.615,
                "longitude" => 120.715,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 13,
                "barangay_id" => 37175,
                "latitude" => 17.62,
                "longitude" => 120.72,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1400,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 14,
                "barangay_id" => 37178,
                "latitude" => 17.7,
                "longitude" => 120.8,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 226,
                "population" => 900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 15,
                "barangay_id" => 37179,
                "latitude" => 17.705,
                "longitude" => 120.805,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 239,
                "population" => 950,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 16,
                "barangay_id" => 37180,
                "latitude" => 17.71,
                "longitude" => 120.81,
                "site_status" => 4,
                "no_purok" => 3,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 98,
                "population" => 1000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 17,
                "barangay_id" => 37200,
                "latitude" => 17.5262,
                "longitude" => 120.6812,
                "site_status" => 4,
                "no_purok" => 5,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 319,
                "population" => 700,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 18,
                "barangay_id" => 37201,
                "latitude" => 17.528,
                "longitude" => 120.683,
                "site_status" => 4,
                "no_purok" => 3,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 155,
                "population" => 800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 19,
                "barangay_id" => 37202,
                "latitude" => 17.53,
                "longitude" => 120.685,
                "site_status" => 4,
                "no_purok" => 3,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 231,
                "population" => 750,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 20,
                "barangay_id" => 37216,
                "latitude" => 17.6249,
                "longitude" => 121.0433,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 650,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 21,
                "barangay_id" => 37222,
                "latitude" => 17.4323,
                "longitude" => 120.7056,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 22,
                "barangay_id" => 37227,
                "latitude" => 17.43,
                "longitude" => 120.71,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 23,
                "barangay_id" => 37230,
                "latitude" => 17.428,
                "longitude" => 120.712,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 950,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 24,
                "barangay_id" => 37235,
                "latitude" => 17.5309,
                "longitude" => 120.6462,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 182,
                "population" => 1300,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 25,
                "barangay_id" => 37284,
                "latitude" => 17.4961,
                "longitude" => 120.6051,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 26,
                "barangay_id" => 37286,
                "latitude" => 17.49,
                "longitude" => 120.61,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 700,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 27,
                "barangay_id" => 37290,
                "latitude" => 17.485,
                "longitude" => 120.615,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 750,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 28,
                "barangay_id" => 37293,
                "latitude" => 17.6766,
                "longitude" => 120.7378,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 29,
                "barangay_id" => 37306,
                "latitude" => 17.682,
                "longitude" => 120.745,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 950,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 30,
                "barangay_id" => 37309,
                "latitude" => 17.683,
                "longitude" => 120.748,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 31,
                "barangay_id" => 37312,
                "latitude" => 17.5,
                "longitude" => 120.55,
                "site_status" => 4,
                "no_purok" => 2,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 155,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 32,
                "barangay_id" => 37313,
                "latitude" => 17.5192,
                "longitude" => 120.5357,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 190,
                "population" => 1100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 33,
                "barangay_id" => 37318,
                "latitude" => 17.5935,
                "longitude" => 120.7018,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1400,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 34,
                "barangay_id" => 37323,
                "latitude" => 17.6213,
                "longitude" => 120.6777,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1300,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 35,
                "barangay_id" => 37324,
                "latitude" => 17.6061,
                "longitude" => 120.6471,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 36,
                "barangay_id" => 37329,
                "latitude" => 17.7507,
                "longitude" => 120.8336,
                "site_status" => 4,
                "no_purok" => 3,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 242,
                "population" => 550,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 37,
                "barangay_id" => 37330,
                "latitude" => 17.755,
                "longitude" => 120.83,
                "site_status" => 4,
                "no_purok" => 3,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 41,
                "population" => 600,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 38,
                "barangay_id" => 37336,
                "latitude" => 17.76,
                "longitude" => 120.835,
                "site_status" => 4,
                "no_purok" => 2,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 49,
                "population" => 500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 39,
                "barangay_id" => 37338,
                "latitude" => 17.2194,
                "longitude" => 120.7703,
                "site_status" => 4,
                "no_purok" => 2,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 108,
                "population" => 700,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 40,
                "barangay_id" => 37339,
                "latitude" => 17.3058,
                "longitude" => 120.7308,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 107,
                "population" => 650,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 41,
                "barangay_id" => 37347,
                "latitude" => 17.225,
                "longitude" => 120.765,
                "site_status" => 4,
                "no_purok" => 3,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 42,
                "population" => 600,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 42,
                "barangay_id" => 37359,
                "latitude" => 16.638,
                "longitude" => 120.719,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 401,
                "population" => 800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 43,
                "barangay_id" => 37362,
                "latitude" => 16.6409,
                "longitude" => 120.7158,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 322,
                "population" => 900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 44,
                "barangay_id" => 37361,
                "latitude" => 16.5636,
                "longitude" => 120.6689,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 532,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 45,
                "barangay_id" => 37494,
                "latitude" => 16.8833,
                "longitude" => 120.6811,
                "site_status" => 4,
                "no_purok" => 10,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 170,
                "population" => 500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 46,
                "barangay_id" => 37495,
                "latitude" => 16.8244,
                "longitude" => 120.7219,
                "site_status" => 4,
                "no_purok" => 26,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 580,
                "population" => 600,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 47,
                "barangay_id" => 37497,
                "latitude" => 16.7822,
                "longitude" => 120.6127,
                "site_status" => 4,
                "no_purok" => 38,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 414,
                "population" => 550,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 48,
                "barangay_id" => 37502,
                "latitude" => 16.4036,
                "longitude" => 120.7931,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 315,
                "population" => 700,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 49,
                "barangay_id" => 37506,
                "latitude" => 16.5502,
                "longitude" => 120.766,
                "site_status" => 4,
                "no_purok" => 3,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 208,
                "population" => 800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 50,
                "barangay_id" => 37507,
                "latitude" => 16.3691,
                "longitude" => 120.8349,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 237,
                "population" => 750,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 51,
                "barangay_id" => 37512,
                "latitude" => 16.695,
                "longitude" => 120.8532,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 588,
                "population" => 900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 52,
                "barangay_id" => 37521,
                "latitude" => 16.7,
                "longitude" => 120.86,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 1100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 53,
                "barangay_id" => 37523,
                "latitude" => 16.71,
                "longitude" => 120.865,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 817,
                "population" => 1000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 54,
                "barangay_id" => 37535,
                "latitude" => 16.7,
                "longitude" => 120.87,
                "site_status" => 4,
                "no_purok" => 34,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 684,
                "population" => 400,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 55,
                "barangay_id" => 37536,
                "latitude" => 16.705,
                "longitude" => 120.875,
                "site_status" => 4,
                "no_purok" => 26,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 534,
                "population" => 450,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 56,
                "barangay_id" => 37543,
                "latitude" => 16.71,
                "longitude" => 120.88,
                "site_status" => 4,
                "no_purok" => 15,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 265,
                "population" => 500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 57,
                "barangay_id" => 37554,
                "latitude" => 16.633,
                "longitude" => 120.637,
                "site_status" => 4,
                "no_purok" => 8,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 226,
                "population" => 800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 58,
                "barangay_id" => 37559,
                "latitude" => 16.64,
                "longitude" => 120.63,
                "site_status" => 4,
                "no_purok" => 12,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 522,
                "population" => 750,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 59,
                "barangay_id" => 37560,
                "latitude" => 16.645,
                "longitude" => 120.625,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 416,
                "population" => 700,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 60,
                "barangay_id" => 37596,
                "latitude" => 16.5,
                "longitude" => 120.58,
                "site_status" => 4,
                "no_purok" => 18,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 181,
                "population" => 900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 61,
                "barangay_id" => 37601,
                "latitude" => 16.505,
                "longitude" => 120.585,
                "site_status" => 4,
                "no_purok" => 16,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 400,
                "population" => 1000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 62,
                "barangay_id" => 37602,
                "latitude" => 16.51,
                "longitude" => 120.59,
                "site_status" => 4,
                "no_purok" => 8,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 168,
                "population" => 950,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 63,
                "barangay_id" => 37604,
                "latitude" => 16.3,
                "longitude" => 120.6,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 639,
                "population" => 1500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 64,
                "barangay_id" => 37606,
                "latitude" => 16.32,
                "longitude" => 120.61,
                "site_status" => 4,
                "no_purok" => 21,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 2,
                "population" => 1400,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 65,
                "barangay_id" => 37613,
                "latitude" => 16.34,
                "longitude" => 120.62,
                "site_status" => 4,
                "no_purok" => 13,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 2,
                "population" => 1300,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 66,
                "barangay_id" => 37617,
                "latitude" => 16.583,
                "longitude" => 120.65,
                "site_status" => 4,
                "no_purok" => 21,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 1100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 67,
                "barangay_id" => 37621,
                "latitude" => 16.59,
                "longitude" => 120.655,
                "site_status" => 4,
                "no_purok" => 13,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 658,
                "population" => 1000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 68,
                "barangay_id" => 37622,
                "latitude" => 16.595,
                "longitude" => 120.66,
                "site_status" => 4,
                "no_purok" => 12,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 950,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 69,
                "barangay_id" => 37646,
                "latitude" => 16.8,
                "longitude" => 121.1,
                "site_status" => 4,
                "no_purok" => 66,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 368,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 70,
                "barangay_id" => 37647,
                "latitude" => 16.79,
                "longitude" => 121.11,
                "site_status" => 4,
                "no_purok" => 68,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 257,
                "population" => 900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 71,
                "barangay_id" => 37648,
                "latitude" => 16.81,
                "longitude" => 121.12,
                "site_status" => 4,
                "no_purok" => 66,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 451,
                "population" => 800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 72,
                "barangay_id" => 37657,
                "latitude" => 16.74,
                "longitude" => 121.07,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 421,
                "population" => 1000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 73,
                "barangay_id" => 37660,
                "latitude" => 16.73,
                "longitude" => 121.06,
                "site_status" => 4,
                "no_purok" => 10,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 358,
                "population" => 1100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 74,
                "barangay_id" => 37661,
                "latitude" => 16.72,
                "longitude" => 121.05,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 202,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 75,
                "barangay_id" => 37670,
                "latitude" => 16.8,
                "longitude" => 121,
                "site_status" => 4,
                "no_purok" => 8,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 76,
                "barangay_id" => 37674,
                "latitude" => 16.79,
                "longitude" => 121.01,
                "site_status" => 4,
                "no_purok" => 27,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1400,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 77,
                "barangay_id" => 37676,
                "latitude" => 16.78,
                "longitude" => 121.02,
                "site_status" => 4,
                "no_purok" => 22,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1300,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 78,
                "barangay_id" => 37692,
                "latitude" => 16.76,
                "longitude" => 121.12,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 79,
                "barangay_id" => 37700,
                "latitude" => 16.75,
                "longitude" => 121.13,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1600,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 80,
                "barangay_id" => 37702,
                "latitude" => 16.74,
                "longitude" => 121.14,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 81,
                "barangay_id" => 37707,
                "latitude" => 16.9,
                "longitude" => 121.25,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 256,
                "population" => 600,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 82,
                "barangay_id" => 37712,
                "latitude" => 16.91,
                "longitude" => 121.26,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 245,
                "population" => 700,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 83,
                "barangay_id" => 37728,
                "latitude" => 16.92,
                "longitude" => 121.27,
                "site_status" => 4,
                "no_purok" => 8,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 99,
                "population" => 650,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 84,
                "barangay_id" => 37754,
                "latitude" => 16.96,
                "longitude" => 121.42,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 85,
                "barangay_id" => 37758,
                "latitude" => 16.955,
                "longitude" => 121.415,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 550,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 86,
                "barangay_id" => 37766,
                "latitude" => 16.9522,
                "longitude" => 121.4131,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 2,
                "population" => 600,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 87,
                "barangay_id" => 37779,
                "latitude" => 16.7722,
                "longitude" => 120.9255,
                "site_status" => 4,
                "no_purok" => 36,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 2,
                "population" => 400,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 88,
                "barangay_id" => 37781,
                "latitude" => 16.7279,
                "longitude" => 120.9773,
                "site_status" => 4,
                "no_purok" => 35,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 450,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 89,
                "barangay_id" => 37790,
                "latitude" => 16.7705,
                "longitude" => 120.9815,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 90,
                "barangay_id" => 37793,
                "latitude" => 16.6189,
                "longitude" => 121.0217,
                "site_status" => 4,
                "no_purok" => 25,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 4,
                "population" => 700,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 91,
                "barangay_id" => 37794,
                "latitude" => 16.6486,
                "longitude" => 121.0932,
                "site_status" => 4,
                "no_purok" => 35,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 750,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 92,
                "barangay_id" => 37796,
                "latitude" => 16.6786,
                "longitude" => 121.0168,
                "site_status" => 4,
                "no_purok" => 50,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 93,
                "barangay_id" => 37816,
                "latitude" => 17.3794,
                "longitude" => 121.2875,
                "site_status" => 4,
                "no_purok" => 12,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 118,
                "population" => 900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 94,
                "barangay_id" => 37818,
                "latitude" => 17.3844,
                "longitude" => 121.2806,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 138,
                "population" => 950,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 95,
                "barangay_id" => 37821,
                "latitude" => 17.39,
                "longitude" => 121.29,
                "site_status" => 4,
                "no_purok" => 3,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 195,
                "population" => 800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 96,
                "barangay_id" => 37825,
                "latitude" => 17.41,
                "longitude" => 121.18,
                "site_status" => 4,
                "no_purok" => 9,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 207,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 97,
                "barangay_id" => 37827,
                "latitude" => 17.42,
                "longitude" => 121.19,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 77,
                "population" => 1100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 98,
                "barangay_id" => 37835,
                "latitude" => 17.425,
                "longitude" => 121.195,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 98,
                "population" => 1000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 99,
                "barangay_id" => 37837,
                "latitude" => 17.565,
                "longitude" => 121.34,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 241,
                "population" => 1500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 100,
                "barangay_id" => 37852,
                "latitude" => 17.57,
                "longitude" => 121.345,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 467,
                "population" => 1400,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 101,
                "barangay_id" => 37854,
                "latitude" => 17.575,
                "longitude" => 121.35,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 242,
                "population" => 1300,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 102,
                "barangay_id" => 37862,
                "latitude" => 17.46,
                "longitude" => 121.47,
                "site_status" => 4,
                "no_purok" => 8,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 306,
                "population" => 2000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 103,
                "barangay_id" => 37872,
                "latitude" => 17.465,
                "longitude" => 121.475,
                "site_status" => 4,
                "no_purok" => 8,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 180,
                "population" => 1800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 104,
                "barangay_id" => 37873,
                "latitude" => 17.47,
                "longitude" => 121.48,
                "site_status" => 4,
                "no_purok" => 17,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 206,
                "population" => 1700,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 105,
                "barangay_id" => 37874,
                "latitude" => 17.4481,
                "longitude" => 121.4571,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 3000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 106,
                "barangay_id" => 37878,
                "latitude" => 17.446,
                "longitude" => 121.46,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 375,
                "population" => 2800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 107,
                "barangay_id" => 37886,
                "latitude" => 17.45,
                "longitude" => 121.465,
                "site_status" => 4,
                "no_purok" => 11,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 2500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 108,
                "barangay_id" => 37891,
                "latitude" => 17.455,
                "longitude" => 121.47,
                "site_status" => 4,
                "no_purok" => 14,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 751,
                "population" => 2200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 109,
                "barangay_id" => 37892,
                "latitude" => 17.46,
                "longitude" => 121.475,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 740,
                "population" => 2100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 110,
                "barangay_id" => 37894,
                "latitude" => 17.465,
                "longitude" => 121.48,
                "site_status" => 4,
                "no_purok" => 8,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 302,
                "population" => 1900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 111,
                "barangay_id" => 37898,
                "latitude" => 17.47,
                "longitude" => 121.485,
                "site_status" => 4,
                "no_purok" => 8,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 323,
                "population" => 1800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 112,
                "barangay_id" => 37934,
                "latitude" => 17.3083,
                "longitude" => 121.185,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 223,
                "population" => 1300,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 113,
                "barangay_id" => 37940,
                "latitude" => 17.315,
                "longitude" => 121.19,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 98,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 114,
                "barangay_id" => 37944,
                "latitude" => 17.32,
                "longitude" => 121.195,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 103,
                "population" => 1100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 115,
                "barangay_id" => 37953,
                "latitude" => 17.0333,
                "longitude" => 121.0833,
                "site_status" => 4,
                "no_purok" => 11,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 192,
                "population" => 500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 116,
                "barangay_id" => 37956,
                "latitude" => 17.05,
                "longitude" => 121.1,
                "site_status" => 4,
                "no_purok" => 5,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 101,
                "population" => 600,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 117,
                "barangay_id" => 37961,
                "latitude" => 17.04,
                "longitude" => 121.09,
                "site_status" => 4,
                "no_purok" => 10,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 201,
                "population" => 550,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 118,
                "barangay_id" => 37974,
                "latitude" => 16.9333,
                "longitude" => 120.8333,
                "site_status" => 4,
                "no_purok" => 5,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 380,
                "population" => 1000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 119,
                "barangay_id" => 37976,
                "latitude" => 16.95,
                "longitude" => 120.85,
                "site_status" => 4,
                "no_purok" => 11,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 705,
                "population" => 900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 120,
                "barangay_id" => 37977,
                "latitude" => 16.94,
                "longitude" => 120.84,
                "site_status" => 4,
                "no_purok" => 10,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 999,
                "population" => 850,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 121,
                "barangay_id" => 37991,
                "latitude" => 17.0833,
                "longitude" => 120.7833,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 700,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 122,
                "barangay_id" => 37993,
                "latitude" => 17.09,
                "longitude" => 120.79,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 123,
                "barangay_id" => 37997,
                "latitude" => 17.1,
                "longitude" => 120.8,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 750,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 124,
                "barangay_id" => 38004,
                "latitude" => 17.0833,
                "longitude" => 120.9833,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 148,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 125,
                "barangay_id" => 38005,
                "latitude" => 17.07,
                "longitude" => 120.98,
                "site_status" => 4,
                "no_purok" => 5,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 206,
                "population" => 1100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 126,
                "barangay_id" => 38008,
                "latitude" => 17.06,
                "longitude" => 120.97,
                "site_status" => 4,
                "no_purok" => 10,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 300,
                "population" => 1000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 127,
                "barangay_id" => 38018,
                "latitude" => 17.1333,
                "longitude" => 121.3333,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 128,
                "barangay_id" => 38022,
                "latitude" => 17.12,
                "longitude" => 121.32,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 850,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 129,
                "barangay_id" => 38024,
                "latitude" => 17.11,
                "longitude" => 121.31,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 950,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 130,
                "barangay_id" => 38029,
                "latitude" => 17.25,
                "longitude" => 121.4,
                "site_status" => 4,
                "no_purok" => 40,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 1500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 131,
                "barangay_id" => 38032,
                "latitude" => 17.24,
                "longitude" => 121.39,
                "site_status" => 4,
                "no_purok" => 10,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 658,
                "population" => 1400,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 132,
                "barangay_id" => 38034,
                "latitude" => 17.23,
                "longitude" => 121.38,
                "site_status" => 4,
                "no_purok" => 23,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 1600,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 133,
                "barangay_id" => 38037,
                "latitude" => 17,
                "longitude" => 120.85,
                "site_status" => 4,
                "no_purok" => 8,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 108,
                "population" => 1000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 134,
                "barangay_id" => 38042,
                "latitude" => 17.01,
                "longitude" => 120.86,
                "site_status" => 4,
                "no_purok" => 5,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 164,
                "population" => 900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 135,
                "barangay_id" => 38045,
                "latitude" => 17.02,
                "longitude" => 120.87,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 213,
                "population" => 950,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 136,
                "barangay_id" => 38050,
                "latitude" => 17.15,
                "longitude" => 120.95,
                "site_status" => 4,
                "no_purok" => 10,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 172,
                "population" => 600,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 137,
                "barangay_id" => 38052,
                "latitude" => 17.16,
                "longitude" => 120.96,
                "site_status" => 4,
                "no_purok" => 18,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 474,
                "population" => 700,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 138,
                "barangay_id" => 38056,
                "latitude" => 17.17,
                "longitude" => 120.97,
                "site_status" => 4,
                "no_purok" => 5,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 215,
                "population" => 650,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 139,
                "barangay_id" => 38067,
                "latitude" => 17.0833,
                "longitude" => 120.9,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 101,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 140,
                "barangay_id" => 38071,
                "latitude" => 17.09,
                "longitude" => 120.91,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 123,
                "population" => 1100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 141,
                "barangay_id" => 38076,
                "latitude" => 17.1,
                "longitude" => 120.92,
                "site_status" => 4,
                "no_purok" => 3,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 90,
                "population" => 1000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 142,
                "barangay_id" => 38084,
                "latitude" => 16.95,
                "longitude" => 120.85,
                "site_status" => 4,
                "no_purok" => 2,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 60,
                "population" => 1300,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 143,
                "barangay_id" => 38085,
                "latitude" => 16.96,
                "longitude" => 120.86,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 318,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 144,
                "barangay_id" => 38090,
                "latitude" => 16.97,
                "longitude" => 120.87,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 108,
                "population" => 1100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 145,
                "barangay_id" => 38123,
                "latitude" => 17.6333,
                "longitude" => 121.2833,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 146,
                "barangay_id" => 38126,
                "latitude" => 17.65,
                "longitude" => 121.3,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 147,
                "barangay_id" => 38129,
                "latitude" => 17.64,
                "longitude" => 121.29,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 148,
                "barangay_id" => 38135,
                "latitude" => 18.25,
                "longitude" => 121.4,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 454,
                "population" => 700,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 149,
                "barangay_id" => 38145,
                "latitude" => 18.26,
                "longitude" => 121.41,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 267,
                "population" => 800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 150,
                "barangay_id" => 38147,
                "latitude" => 18.27,
                "longitude" => 121.42,
                "site_status" => 4,
                "no_purok" => 9,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 495,
                "population" => 900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 151,
                "barangay_id" => 38154,
                "latitude" => 17.9474,
                "longitude" => 121.1092,
                "site_status" => 4,
                "no_purok" => 3,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 152,
                "barangay_id" => 38163,
                "latitude" => 18.0488,
                "longitude" => 121.096,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 153,
                "barangay_id" => 38166,
                "latitude" => 17.8941,
                "longitude" => 121.0526,
                "site_status" => 4,
                "no_purok" => 5,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 0,
                "population" => 1000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 154,
                "barangay_id" => 38216,
                "latitude" => 18.2943,
                "longitude" => 121.4261,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 362,
                "population" => 1500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 155,
                "barangay_id" => 38217,
                "latitude" => 18.216,
                "longitude" => 121.4717,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 266,
                "population" => 1400,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 156,
                "barangay_id" => 38227,
                "latitude" => 18.2519,
                "longitude" => 121.477,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 161,
                "population" => 1300,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 157,
                "barangay_id" => 37365,
                "latitude" => 16.4046,
                "longitude" => 120.5636,
                "site_status" => 4,
                "no_purok" => 8,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 3,
                "population" => 2500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 158,
                "barangay_id" => 37424,
                "latitude" => 16.3935,
                "longitude" => 120.5862,
                "site_status" => 4,
                "no_purok" => 2,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 106,
                "population" => 3000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 159,
                "barangay_id" => 37367,
                "latitude" => 16.398,
                "longitude" => 120.584,
                "site_status" => 4,
                "no_purok" => 12,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 3,
                "population" => 3200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 160,
                "barangay_id" => 37368,
                "latitude" => 16.4025,
                "longitude" => 120.615,
                "site_status" => 4,
                "no_purok" => 12,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 3,
                "population" => 3100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 161,
                "barangay_id" => 37370,
                "latitude" => 16.3989,
                "longitude" => 120.6035,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 715,
                "population" => 2800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 162,
                "barangay_id" => 37372,
                "latitude" => 16.419,
                "longitude" => 120.6155,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 341,
                "population" => 2700,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 163,
                "barangay_id" => 37377,
                "latitude" => 16.412,
                "longitude" => 120.594,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 3,
                "population" => 2900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 164,
                "barangay_id" => 37376,
                "latitude" => 16.391,
                "longitude" => 120.61,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 735,
                "population" => 3000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 165,
                "barangay_id" => 37382,
                "latitude" => 16.402,
                "longitude" => 120.62,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 500,
                "population" => 2600,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 166,
                "barangay_id" => 37386,
                "latitude" => 16.417,
                "longitude" => 120.61,
                "site_status" => 4,
                "no_purok" => 9,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 588,
                "population" => 2500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 167,
                "barangay_id" => 37468,
                "latitude" => 16.43,
                "longitude" => 120.6,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 2800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 168,
                "barangay_id" => 37389,
                "latitude" => 16.426,
                "longitude" => 120.61,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 2,
                "population" => 2900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 169,
                "barangay_id" => 37477,
                "latitude" => 16.418,
                "longitude" => 120.625,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 784,
                "population" => 3200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 170,
                "barangay_id" => 37393,
                "latitude" => 16.42,
                "longitude" => 120.61,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 2,
                "population" => 3100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 171,
                "barangay_id" => 37396,
                "latitude" => 16.4167,
                "longitude" => 120.57,
                "site_status" => 4,
                "no_purok" => 5,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 451,
                "population" => 3000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 172,
                "barangay_id" => 37369,
                "latitude" => 16.39,
                "longitude" => 120.59,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 733,
                "population" => 2700,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 173,
                "barangay_id" => 37401,
                "latitude" => 16.395,
                "longitude" => 120.62,
                "site_status" => 4,
                "no_purok" => 32,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 9,
                "population" => 3500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 174,
                "barangay_id" => 37403,
                "latitude" => 16.4,
                "longitude" => 120.63,
                "site_status" => 4,
                "no_purok" => 8,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 3300,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 175,
                "barangay_id" => 37478,
                "latitude" => 16.428,
                "longitude" => 120.598,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 3400,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 176,
                "barangay_id" => 37405,
                "latitude" => 16.408,
                "longitude" => 120.6,
                "site_status" => 4,
                "no_purok" => 8,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 3,
                "population" => 3600,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 177,
                "barangay_id" => 37413,
                "latitude" => 16.415,
                "longitude" => 120.605,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 568,
                "population" => 3200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 178,
                "barangay_id" => 37419,
                "latitude" => 16.42,
                "longitude" => 120.61,
                "site_status" => 4,
                "no_purok" => 6,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 415,
                "population" => 3100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 179,
                "barangay_id" => 37421,
                "latitude" => 16.41,
                "longitude" => 120.625,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 743,
                "population" => 3000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 180,
                "barangay_id" => 37433,
                "latitude" => 16.4125,
                "longitude" => 120.62,
                "site_status" => 4,
                "no_purok" => 3,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 454,
                "population" => 2900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 181,
                "barangay_id" => 37426,
                "latitude" => 16.425,
                "longitude" => 120.59,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 652,
                "population" => 2800,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 182,
                "barangay_id" => 37427,
                "latitude" => 16.41,
                "longitude" => 120.58,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 3300,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 183,
                "barangay_id" => 37481,
                "latitude" => 16.4155,
                "longitude" => 120.595,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 824,
                "population" => 3400,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 184,
                "barangay_id" => 37430,
                "latitude" => 16.42,
                "longitude" => 120.585,
                "site_status" => 4,
                "no_purok" => 10,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 2,
                "population" => 3500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 185,
                "barangay_id" => 37431,
                "latitude" => 16.418,
                "longitude" => 120.58,
                "site_status" => 4,
                "no_purok" => 4,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 894,
                "population" => 3200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 186,
                "barangay_id" => 37387,
                "latitude" => 16.416,
                "longitude" => 120.575,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 3600,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 187,
                "barangay_id" => 37418,
                "latitude" => 16.419,
                "longitude" => 120.618,
                "site_status" => 4,
                "no_purok" => 0,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 814,
                "population" => 3500,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 188,
                "barangay_id" => 37448,
                "latitude" => 16.417,
                "longitude" => 120.61,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 3000,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 189,
                "barangay_id" => 37437,
                "latitude" => 16.408,
                "longitude" => 120.6,
                "site_status" => 4,
                "no_purok" => 8,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 2,
                "population" => 3200,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 190,
                "barangay_id" => 37438,
                "latitude" => 16.41,
                "longitude" => 120.605,
                "site_status" => 4,
                "no_purok" => 3,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 251,
                "population" => 3100,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 191,
                "barangay_id" => 37439,
                "latitude" => 16.396,
                "longitude" => 120.615,
                "site_status" => 4,
                "no_purok" => 5,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 1,
                "population" => 3300,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 192,
                "barangay_id" => 37488,
                "latitude" => 16.41,
                "longitude" => 120.61,
                "site_status" => 4,
                "no_purok" => 11,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 742,
                "population" => 2900,
                "created_at" => null,
                "updated_at" => null,
            ],
            [
                "site_id" => 193,
                "barangay_id" => 37453,
                "latitude" => 16.413,
                "longitude" => 120.612,
                "site_status" => 4,
                "no_purok" => 7,
                "no_sitio" => 0,
                "target_purok" => 0,
                "target_sitio" => 0,
                "no_household" => 767,
                "population" => 2800,
                "created_at" => null,
                "updated_at" => null,
            ],
        ];

        Pkp_site::insert($data);
    }
}
